"""init_sqlite

Revision ID: 75174a1c4b3c
Revises: 
Create Date: 2026-06-22 15:42:53.182816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75174a1c4b3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_vehicles_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_name'), 'gates', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'OPERATOR', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BUS', 'TRUCK', 'AMBULANCE', 'MOTORCYCLE', 'OTHER', name='vehicletype'), nullable=False),
    sa.Column('vehicle_category', sa.Enum('VIP', 'EMERGENCY', 'STAFF', 'VENDOR', 'GENERAL', name='vehiclecategory'), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('blacklisted_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED', name='permissionstatus'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_mobile_number', sa.String(length=15), nullable=True),
    sa.Column('driver_license_number', sa.String(length=50), nullable=True),
    sa.Column('license_valid_until', sa.Date(), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('start_point', sa.String(length=255), nullable=True),
    sa.Column('end_point', sa.String(length=255), nullable=True),
    sa.Column('route_details', sa.Text(), nullable=True),
    sa.Column('purpose_category', sa.Enum('VIP', 'EMERGENCY', 'STAFF', 'VENDOR', 'GENERAL', 'GOVERNMENT', 'MEDIA', 'OTHER', name='purposecategory'), nullable=True),
    sa.Column('expected_occupants', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=15), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_valid_until', sa.Date(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('rc_url', sa.Text(), nullable=True),
    sa.Column('dl_url', sa.Text(), nullable=True),
    sa.Column('vehicle_photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_permissions_permission_code'), 'permissions', ['permission_code'], unique=True)
    op.create_index(op.f('ix_permissions_requester_id'), 'permissions', ['requester_id'], unique=False)
    op.create_index(op.f('ix_permissions_status'), 'permissions', ['status'], unique=False)
    op.create_index(op.f('ix_permissions_vehicle_id'), 'permissions', ['vehicle_id'], unique=False)
    op.create_table('entry_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=True),
    sa.Column('gate_id', sa.Uuid(), nullable=False),
    sa.Column('scanned_by', sa.Uuid(), nullable=False),
    sa.Column('scan_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='scandirection'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'DENIED_EXPIRED', 'DENIED_INVALID_GATE', 'DENIED_REVOKED', 'DUPLICATE_SCAN', 'BLACKLISTED', 'OVERRIDE_GRANTED', name='logstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('override_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_logs_gate_id'), 'entry_logs', ['gate_id'], unique=False)
    op.create_index(op.f('ix_entry_logs_permission_id'), 'entry_logs', ['permission_id'], unique=False)
    op.create_index(op.f('ix_entry_logs_scanned_by'), 'entry_logs', ['scanned_by'], unique=False)
    op.create_table('permission_gates',
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('gate_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'gate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_gates')
    op.drop_index(op.f('ix_entry_logs_scanned_by'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_permission_id'), table_name='entry_logs')
    op.drop_index(op.f('ix_entry_logs_gate_id'), table_name='entry_logs')
    op.drop_table('entry_logs')
    op.drop_index(op.f('ix_permissions_vehicle_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_status'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_requester_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_permission_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('blacklisted_vehicles')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gates_name'), table_name='gates')
    op.drop_table('gates')
    # ### end Alembic commands ###
