"""expand_permission_schema_with_insurance_and_admin

Revision ID: 9e0e15eac6c8
Revises: 0001_initial_schema
Create Date: 2026-06-21 21:33:28.566836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9e0e15eac6c8'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    purposecategory = postgresql.ENUM('VIP', 'EMERGENCY', 'STAFF', 'VENDOR', 'GENERAL', 'GOVERNMENT', 'MEDIA', 'OTHER', name='purposecategory')
    purposecategory.create(op.get_bind(), checkfirst=True)
    
    op.drop_constraint('gates_name_key', 'gates', type_='unique')
    op.drop_index('ix_gates_name', table_name='gates')
    op.create_index(op.f('ix_gates_name'), 'gates', ['name'], unique=True)
    op.add_column('permissions', sa.Column('driver_name', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('driver_mobile_number', sa.String(length=15), nullable=True))
    op.add_column('permissions', sa.Column('driver_license_number', sa.String(length=50), nullable=True))
    op.add_column('permissions', sa.Column('license_valid_until', sa.Date(), nullable=True))
    op.add_column('permissions', sa.Column('time_from', sa.Time(), nullable=True))
    op.add_column('permissions', sa.Column('time_to', sa.Time(), nullable=True))
    op.add_column('permissions', sa.Column('start_point', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('end_point', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('route_details', sa.Text(), nullable=True))
    op.add_column('permissions', sa.Column('purpose_category', sa.Enum('VIP', 'EMERGENCY', 'STAFF', 'VENDOR', 'GENERAL', 'GOVERNMENT', 'MEDIA', 'OTHER', name='purposecategory'), nullable=True))
    op.add_column('permissions', sa.Column('expected_occupants', sa.Integer(), nullable=True))
    op.add_column('permissions', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('permissions', sa.Column('emergency_contact_number', sa.String(length=15), nullable=True))
    op.add_column('permissions', sa.Column('insurance_policy_number', sa.String(length=100), nullable=True))
    op.add_column('permissions', sa.Column('insurance_valid_until', sa.Date(), nullable=True))
    op.add_column('permissions', sa.Column('admin_remarks', sa.Text(), nullable=True))
    op.add_column('permissions', sa.Column('rc_url', sa.Text(), nullable=True))
    op.add_column('permissions', sa.Column('dl_url', sa.Text(), nullable=True))
    op.add_column('permissions', sa.Column('vehicle_photo_url', sa.Text(), nullable=True))
    op.drop_constraint('permissions_permission_code_key', 'permissions', type_='unique')
    op.drop_index('ix_permissions_permission_code', table_name='permissions')
    op.create_index(op.f('ix_permissions_permission_code'), 'permissions', ['permission_code'], unique=True)
    op.drop_constraint('vehicles_license_plate_key', 'vehicles', type_='unique')
    op.drop_index('ix_vehicles_license_plate', table_name='vehicles')
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.create_index('ix_vehicles_license_plate', 'vehicles', ['license_plate'], unique=False)
    op.create_unique_constraint('vehicles_license_plate_key', 'vehicles', ['license_plate'])
    op.drop_index(op.f('ix_permissions_permission_code'), table_name='permissions')
    op.create_index('ix_permissions_permission_code', 'permissions', ['permission_code'], unique=False)
    op.create_unique_constraint('permissions_permission_code_key', 'permissions', ['permission_code'])
    op.drop_column('permissions', 'vehicle_photo_url')
    op.drop_column('permissions', 'dl_url')
    op.drop_column('permissions', 'rc_url')
    op.drop_column('permissions', 'admin_remarks')
    op.drop_column('permissions', 'insurance_valid_until')
    op.drop_column('permissions', 'insurance_policy_number')
    op.drop_column('permissions', 'emergency_contact_number')
    op.drop_column('permissions', 'emergency_contact_name')
    op.drop_column('permissions', 'organization_name')
    op.drop_column('permissions', 'expected_occupants')
    op.drop_column('permissions', 'purpose_category')
    op.drop_column('permissions', 'route_details')
    op.drop_column('permissions', 'end_point')
    op.drop_column('permissions', 'start_point')
    op.drop_column('permissions', 'time_to')
    op.drop_column('permissions', 'time_from')
    op.drop_column('permissions', 'license_valid_until')
    op.drop_column('permissions', 'driver_license_number')
    op.drop_column('permissions', 'driver_mobile_number')
    op.drop_column('permissions', 'driver_name')
    op.drop_index(op.f('ix_gates_name'), table_name='gates')
    op.create_index('ix_gates_name', 'gates', ['name'], unique=False)
    op.create_unique_constraint('gates_name_key', 'gates', ['name'])
    
    purposecategory = postgresql.ENUM('VIP', 'EMERGENCY', 'STAFF', 'VENDOR', 'GENERAL', 'GOVERNMENT', 'MEDIA', 'OTHER', name='purposecategory')
    purposecategory.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
